### ISSUE TITLE
Variables cannot be overridden

### ISSUE THREAD

**Issue by praseodym** [jnv/ansible-role-debian-backports#2]
The variables defined in `vars/Debian.yml` and `vars/Ubuntu.yml` apparently have a higher precedence than variables defined in the hosts playbook; seems like a weird Ansible design choice to me. This means that `backports_uri` cannot be easily overridden.

Creating a file named `defaults/main.yml` seems most common way to fix this, but I'm not sure how to make this OS-dependant.

**Comment by nevart** [comment]
Hi,

I did run into the same problem, and would like to propose the following fix:

IMHO, as these variables shouldn't be de-facto constansts (the current status quo), but variables (overridable), the propoer place would be `defaults/`, instead of `vars/`.

See [this StackOverflow question and answer](https://stackoverflow.com/questions/29127560/whats-the-difference-between-defaults-and-vars-in-an-ansible-role/29128089#29128089) for some more details.

@jnv If you agree, I'll push a MR.

Thanks for your work, cheers!

**Comment by jnv** [comment]
@nevart Sure, go ahead. Thank you!

**Comment by nevart** [comment]
Unfortunately, I forgot to alter the inclusion of the variables recently: #7 will fix this.
